name: Build and Test

on: [push, pull_request]

env:
  BUILD_TYPE: Debug
  GLOG_v: 4
  GLOG_logtostderr: 1

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      # Allow other jobs to continue when one job fails
      fail-fast: false
      matrix:
        remaster: [none, simple, per_key, counterless]
        lock: [old, rma, ddr]
        exclude:
          - remaster: simple
            lock: rma
          - remaster: simple
            lock: ddr
          - remaster: per_key
            lock: rma
          - remaster: per_key
            lock: ddr
          - remaster: counterless
            lock: old

    steps:
    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: .deps
        key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeFiles.txt') }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: ./install-deps.sh

    - name: Create Build Environment
      run: cmake -E make_directory ${{ github.workspace }}/build

    - name: Configure CMake
      shell: bash
      env:
        REMASTER_PROTOCOL: ${{ matrix.remaster }}
        LOCK_MANAGER: ${{ matrix.lock }}
      working-directory: ${{ github.workspace }}/build
      run: cmake -S $GITHUB_WORKSPACE -B . 
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE 
        -DBUILD_SLOG_CLIENT=OFF 
        -DBUILD_SLOG_TESTS=ON
        -DREMASTER_PROTOCOL=$REMASTER_PROTOCOL
        -DLOCK_MANAGER=$LOCK_MANAGER

    - name: Build
      working-directory: ${{ github.workspace }}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --parallel 4

    - name: Test
      working-directory: ${{ github.workspace }}/build
      shell: bash
      run: ctest -C $BUILD_TYPE --output-on-failure
